//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comet()
        {
            this.FeedbackToComets = new HashSet<FeedbackToComet>();
            this.ImageOfComets = new HashSet<ImageOfComet>();
        }
    
        public int CometID { get; set; }
        public string CometName { get; set; }
        public string EarthMOID { get; set; }
        public string Dimensions { get; set; }
        public string Meandiameter { get; set; }
        public string Mass { get; set; }
        public string Aphelion { get; set; }
        public string Perihelion { get; set; }
        public string DiscoveredBy { get; set; }
        public string DiscoveredDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackToComet> FeedbackToComets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageOfComet> ImageOfComets { get; set; }
    }
}
