//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constellation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constellation()
        {
            this.FeedbacktoConstellations = new HashSet<FeedbacktoConstellation>();
            this.ImageOfConstellations = new HashSet<ImageOfConstellation>();
        }
    
        public int ConstellationID { get; set; }
        public string ConstellationName { get; set; }
        public string Abbreviation { get; set; }
        public string Genitive { get; set; }
        public string Symbolism { get; set; }
        public string Declination { get; set; }
        public string Area { get; set; }
        public string MainStar { get; set; }
        public string Meteor { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbacktoConstellation> FeedbacktoConstellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageOfConstellation> ImageOfConstellations { get; set; }
    }
}
