//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackToComet
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> bit { get; set; }
        public Nullable<int> CometID { get; set; }
    
        public virtual Comet Comet { get; set; }
    }
}
