//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class ImageOfComet
    {
        public int ImageID { get; set; }
        public Nullable<int> CometID { get; set; }
        [DisplayName("Upload File")]
        public string Image { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
        public string Description { get; set; }
    
        public virtual Comet Comet { get; set; }
    }
}
