//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AstronomyEntities : DbContext
    {
        public AstronomyEntities()
            : base("name=AstronomyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comet> Comets { get; set; }
        public virtual DbSet<Constellation> Constellations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FeedbackToComet> FeedbackToComets { get; set; }
        public virtual DbSet<FeedbacktoConstellation> FeedbacktoConstellations { get; set; }
        public virtual DbSet<FeedbackToNew> FeedbackToNews { get; set; }
        public virtual DbSet<FeedbacktoObservatory> FeedbacktoObservatories { get; set; }
        public virtual DbSet<FeedbackToPhenomena> FeedbackToPhenomenas { get; set; }
        public virtual DbSet<FeedbacktoPlanet> FeedbacktoPlanets { get; set; }
        public virtual DbSet<ImageOfComet> ImageOfComets { get; set; }
        public virtual DbSet<ImageOfConstellation> ImageOfConstellations { get; set; }
        public virtual DbSet<ImageOfNew> ImageOfNews { get; set; }
        public virtual DbSet<ImageOfObservatory> ImageOfObservatory { get; set; }
        public virtual DbSet<ImageOfPhenomena> ImageOfPhenomenas { get; set; }
        public virtual DbSet<ImageOfPlanet> ImageOfPlanet { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Observatory> Observatories { get; set; }
        public virtual DbSet<Phenomena> Phenomenas { get; set; }
        public virtual DbSet<Planet> Planets { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
