//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phenomena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phenomena()
        {
            this.FeedbackToPhenomenas = new HashSet<FeedbackToPhenomena>();
            this.ImageOfPhenomenas = new HashSet<ImageOfPhenomena>();
        }
    
        public int PhenomenaID { get; set; }
        public string PhenomenaName { get; set; }
        public string Title { get; set; }
        public Nullable<bool> status { get; set; }
        public string Description { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackToPhenomena> FeedbackToPhenomenas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageOfPhenomena> ImageOfPhenomenas { get; set; }
    }
}
