//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planet()
        {
            this.FeedbacktoPlanets = new HashSet<FeedbacktoPlanet>();
            this.ImageOfPlanets = new HashSet<ImageOfPlanet>();
        }
    
        public int PlanetID { get; set; }
        public string PlanetName { get; set; }
        public string RecordedBy { get; set; }
        public string FirstRecord { get; set; }
        public string SurfaceTemperature { get; set; }
        public string OrbitPeriod { get; set; }
        public string OrbitDistance { get; set; }
        public string Rings { get; set; }
        public string NotableMoons { get; set; }
        public string KnownMoons { get; set; }
        public string EquatorialCircumference { get; set; }
        public string PolarDiameter { get; set; }
        public string EquatorialDiameter { get; set; }
        public string Mass { get; set; }
        public string atmosphere { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbacktoPlanet> FeedbacktoPlanets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageOfPlanet> ImageOfPlanets { get; set; }
    }
}
